@startuml

skinparam monochrome true
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam DefaultFontName arial
skinparam DefaultFontSize 12
skinparam ClassFontStyle bold
skinparam linetype ortho
hide empty fields
hide circle


title Soccerheatmap - Class Diagram

class Player {
 - int id
 - int playerNumber
 - Position position
 - String name

 + getPosition() : Position
 + setPosition(Position) : void
}
class Event {
 - Position event_position
}

class Corner {
  - 
}

class Goal {
  - 
}

class ShotOn {
  - 
}

class Position {
 - int x
 - int y
}

class Team {
 - List players
}

class Match {
 - Team home
 - Lineup homeLineup
 - Team away
 - Lineup awayLineup
}

class Lineup {
 - Map lineup

+ getPosition(int) : Position
+ getPlayer(Position) : int
+ getLineup() : Map
}

@enduml